### PR TITLE
Nominating Justin Downie for the open chair position

### PR DESCRIPTION
**Pull request by dustinblack**
## Changes introduced with this PR

I hereby nominate Justin Downie for the open chair position.

The voting period starts on the 16th of May 2023 and ends on the 23th of May 2023. All current ART members are eligible to vote and are considered for quorum approval.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lmilbaum** [comment]
I am sponsoring

**Comment by tsebastiani** [comment]
I act as sponsor

**Comment by sandrobonazzola** [comment]
I'm sponsoring

**Review by sandrobonazzola — APPROVED** [review]

**Review by lmilbaum — APPROVED** [review]
I would prefer s/criticism/feedback/ :-)

**Comment by ozanunsal** [comment]
I'm sponsoring

**Review by AvlWx2014 — APPROVED** [review]

**Review by jdowni000 — APPROVED** [review]

**Review by mfleader — APPROVED** [review]

**Review by HubertStefanski — APPROVED** [review]

**Review by Harshith-umesh — APPROVED** [review]

**Comment by dustinblack** [comment]
Merging approved with quorum vote from the ART. Welcome to the chair position, @jdowni000!

**Pull request merged**
