### PR TITLE
Carpenter Name 

### PR DESCRIPTION
**Pull request by jdowni000**
## Changes introduced with this PR

Rename Carpenter to `arcalot/arcaflow-container-toolkit` - edited
Move carpenter.yaml reusable workflow file to carpenter project

Voting Period is 7 days
---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dustinblack** [comment]
I generally try to avoid pet names as official names until it becomes clearly valuable or necessary. Using descriptive names can help new users find their way to tools and understand their use cases, and it also helps to curb any potential drawbacks due to ego (once you name it, are you willing to kill it?).

I'm not dead-set against calling it carpenter, since as a development team it's certainly our communication shortcut for the tool already, but I'd like to consider other options and hear other opinions.

**Comment by jdowni000** [comment]
I propose that we simply drop the plugin from the name and it can be officially `arcaflow-image-builder`. Yes, the carpenter tool can do more than simply build, however integrating all its features into a descriptive name could lengthy. I have began to develop a github action of utilizing carpenter [here](https://github.com/arcalot/arcaflow-image-builder-action/tree/main/.gihub/workflows) and the naming convention will line up nicely and make sense in the docs.

**Comment by dustinblack** [comment]
Even "image" is an overloaded term. What about something like "arcaflow-container-toolkit" or "arcaflow-container-actions" ?

**Comment by jdowni000** [comment]
> Even "image" is an overloaded term. What about something like "arcaflow-container-toolkit" or "arcaflow-container-actions" ?

That is a great point. The actions at the end should only reference that action repository where that will live...so with naming convention carpenter would be called 'arcaflow-container' ? I do like 'arcaflow-container-toolkit' and the action could be the same with action on the end

**Comment by dustinblack** [comment]
> > Even "image" is an overloaded term. What about something like "arcaflow-container-toolkit" or "arcaflow-container-actions" ?
> 
> That is a great point. The actions at the end should only reference that action repository where that will live...so with naming convention carpenter would be called 'arcaflow-container' ? I do like 'arcaflow-container-toolkit' and the action could be the same with action on the end

I thought part of the intention alongside the renaming effort was to combine what are now the "image-builder" and the "image-builder-actions" into a single repo. So my thought would be one repo called "arcaflow-container-toolkit" I guess.

**Comment by jdowni000** [comment]
the reusable workflow will live within carpenter. This is no issue and should not be an issue for versioning because from the comments in [PR](https://github.com/arcalot/arcaflow-reusable-workflows/pull/7#:~:text=It%20would%20seem%20that%20creating%20a%20Dockerfile%2Dbased%20Action%20could%20be%20the%20way%20to%20go%20here%20maybe%3F) I will additionally need to make an action out of carpenter. This reusable workflow step in CI process can remain to do the custom tag and img_exp part.  Then pass that info to the action. This part will be version controlled [here](https://github.com/arcalot/arcaflow-container-toolkit-action). So at the EOD, you can call the reusable workflow that handles all your inputs and sets custom things, and then passes that into carpenter as an action. This is a WIP.

**Comment by jdowni000** [comment]
After working with the action repository of carpenter ( More for testing than anything official), I propose now @dustinblack idea of `arcalot/arcaflow-container-toolkit' instead of just carpenter.

**Comment by jdowni000** [comment]
> 

This depends on moving the reusable workflow as well since it is two part. With that said, if approved for both items, we will need to:

- Rename repository
- Move reusable workflow to new repository name
- Update documentation of carpenter and include reusable workflow information in that documentation
- Create a new release with official v1.0.0
- Update official plugins to now point to that reusable workflow location

This will require a ton of work and PR's. Not only in every repository, but in documentation as well. I have began a head start on the new docs ( link in proposal). But it will be important to merge these PR's in a timely fashion once the name has been changed.

**Review by jaredoconnell — APPROVED** [review]
Looks good to me.
I think that the proposed name is a good replacement of the pet name because it is both descriptive and short.
Moving the reusable workflow file into the toolkit repository seems fine to me.

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Comment by tsebastiani** [comment]
LGTM

**Comment by mfleader** [comment]
I'm on board with the proposal. They say, if you love something, you have to be able to let it go its own path.

**Comment by dustinblack** [comment]
> This will require a ton of work and PR's. Not only in every repository, but in documentation as well. I have began a head start on the new docs ( link in proposal). But it will be important to merge these PR's in a timely fashion once the name has been changed.

Can this happen in such a way that the backend work is completed non-disruptively to internal and external plugin repos, and then there is just a final step to update all repos using the action to the new version/path/whatever?

**Comment by jdowni000** [comment]
The reusable workflow points to a repository that will be changing it's name.  The only thing I can think of is if we were to leave the reusable workflow repository for now, update it in main to utilize the action I created the other day ( which is still published atm) with my [fork](https://github.com/jdowni000/arcaflow-reusable-workflows/blob/package/.github/workflows/carpenter.yaml#:~:text=uses%3A%20arcalot/arcaflow%2Dcontainer%2Dtoolkit%2Daction%40v0.1.0), then make all the changes in the carpenter repository. I "think" this would make it so nothing would break as the image is already built and public in ghcr using this image in the action, called by the workflow everyone consumes today. I am unsure but doubt the image would be renamed from renaming the repository. Hope that makes sense.

**Comment by jdowni000** [comment]
So long story short. We leave the update the `arcaflow-reusable-workflow` repository to utilize carpenter as an action that uses a prebuilt carpenter image we have today. Make all the changes in the carpenter repo, where the new reusable workflow file will live, than notify end users and delete the `arcaflow-reusable-workflow` repository while updating all official plugin repos to now use the new reusable workflow path. I thought this comment would be shorter, I was wrong.

**Review by dustinblack — APPROVED** [review]

**Review by Harshith-umesh — APPROVED** [review]
LGTM

**Review by tsebastiani — APPROVED** [review]

**Review by HubertStefanski — APPROVED** [review]

**Pull request merged**
