### PR TITLE
propose retiring arcalog

### PR DESCRIPTION
**Pull request by dustinblack**
## Changes introduced with this PR

Proposal to retire the Arcalog project from the Arcalot org.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dbutenhof — APPROVED** [review]

**Review by jaredoconnell — APPROVED** [review]

**Review by Harshith-umesh — APPROVED** [review]

**Review by webbnh — APPROVED** [review]
👍

**Review by tsebastiani — APPROVED** [review]

**Review by jdowni000 — APPROVED** [review]

**Review by jaredoconnell — APPROVED** [review]

**Review by mfleader — APPROVED** [review]

**Comment by webbnh** [comment]
> [dustinblack](https://github.com/dustinblack) [force-pushed](https://github.com/arcalot/arcalot-round-table/compare/ac06d1e81cfedc62caba427013ef352ed32b3252..4306c04723b026224f557287b96fdda7f750de10) the retire-arcalog branch from [ac06d1e ](https://github.com/arcalot/arcalot-round-table/commit/ac06d1e81cfedc62caba427013ef352ed32b3252)to [4306c04 ](https://github.com/arcalot/arcalot-round-table/commit/4306c04723b026224f557287b96fdda7f750de10)
[20 minutes ago](https://github.com/arcalot/arcalot-round-table/pull/45#event-13104989313)

@dustinblack, what did you change?

**Comment by AvlWx2014** [comment]
Given Arcalog is based on (or inspired by?) a preprint academic paper, is this a safe thing to do with input from the authors? For example, if I were to submit a paper for peer review and the project it inspired (or was based on) was archived I would have preconceptions about that paper before even reviewing it. 

Maybe this isn't worth considering and perhaps the fact that the project has gone undeveloped and unmaintained in that long has a higher weight.

**Review by AvlWx2014 — APPROVED** [review]
Given Arcalog is based on (or inspired by?) a preprint academic paper, is this a safe thing to do with input from the authors? For example, if I were to submit a paper for peer review and the project it inspired (or was based on) was archived I would have preconceptions about that paper before even reviewing it. 

Maybe this isn't worth considering and perhaps the fact that the project has gone undeveloped and unmaintained in that long has a higher weight.

**Comment by dustinblack** [comment]
> Given Arcalog is based on (or inspired by?) a preprint academic paper, is this a safe thing to do with input from the authors? For example, if I were to submit a paper for peer review and the project it inspired (or was based on) was archived I would have preconceptions about that paper before even reviewing it.
> 
> Maybe this isn't worth considering and perhaps the fact that the project has gone undeveloped and unmaintained in that long has a higher weight.

We will be archiving Arcalog, not removing it entirely, and the main author and stakeholder has stopped being involved in the community and in Arcalog for more than year.

**Pull request merged**
